import "./globals.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";

import { cn } from "@/lib/utils";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ModalProvider } from "@/components/providers/modal.provider";
import { SocketProvider } from "@/components/providers/socket-provider";

const globalFont = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Diskord",
  description: "Generated by Diskord",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={cn(globalFont.className, "bg-white dark:bg-[#313338]")}
        >
          <SocketProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
              storageKey="diskord-theme"
            >
              <ModalProvider />
              {children}
            </ThemeProvider>
          </SocketProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
